### ISSUE TITLE
Can't install WixToolset.Util.winext

### ISSUE THREAD

**Issue by emanueljg** [jpakkane/msicreator#13]
I am writing a GitHub Actions to create an MSI on each release. Here's my approach so far:

```yaml
      - name: Install prerequisite packages (Windows)
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: "install swig microsoft-build-tools dotnet"

      - name: Build .msi
        if: matrix.os == 'windows-latest'
        run: |
          # install wix
          dotnet tool install --global wix --version 4.0.2
          wix extension add -g WixToolset.UI.winext
          # run script
          source $VENV
          poetry run poe mkmsi
```
I added the `wix extension` part after getting an error that the extension `WixToolset.UI.wixext` could not be found, but I can't seem to install it:
![msibuild2](https://github.com/jpakkane/msicreator/assets/18590700/2023e320-83ce-4b56-8d49-22fbd871d166)
It appears it fails silently, without stderr. What's up?
